"""inisialisasi database

Revision ID: 840720faa239
Revises: 
Create Date: 2018-05-24 17:15:08.424125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840720faa239'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
