"""inisialisasi database

Revision ID: c9311ee6c77a
Revises: 
Create Date: 2018-05-23 18:25:59.042015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9311ee6c77a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invoice',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('example_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Invoice')
    # ### end Alembic commands ###
