"""inisialiasi database

Revision ID: edfae46b9131
Revises: 
Create Date: 2018-05-24 11:39:00.415690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfae46b9131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('example_data', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.drop_table('Invoice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invoice',
    sa.Column('invoice_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Invoice_invoice_id_seq"\'::regclass)'), nullable=False),
    sa.Column('example_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('invoice_id', name='Invoice_pkey')
    )
    op.drop_table('invoice')
    # ### end Alembic commands ###
